from config.config_env import get_env

sbr_paperid = 24160 if get_env() == 'prod' else 199

syllabuses_expect = [{'no': 1, 'title': '一、选择题', 'type': 1, 'totalscore': 40.0, 'questioncnt': 4, 'details': [
    {'questionid': 268653524, 'no': 1, 'type': 1, 'correct': 0, 'totalscore': 0.0, 'score': None,
     'options': [{'iscorrect': False, 'chosed': False, 'index': 0, 'value': 'A'},
                 {'iscorrect': False, 'chosed': False, 'index': 1, 'value': 'B'},
                 {'iscorrect': False, 'chosed': False, 'index': 2, 'value': 'C'},
                 {'iscorrect': False, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [], 'useranswerindexes': []},
    {'questionid': 268653525, 'no': 2, 'type': 1, 'correct': 0, 'totalscore': 0.0, 'score': None,
     'options': [{'iscorrect': False, 'chosed': False, 'index': 0, 'value': 'A'},
                 {'iscorrect': False, 'chosed': False, 'index': 1, 'value': 'B'},
                 {'iscorrect': False, 'chosed': False, 'index': 2, 'value': 'C'},
                 {'iscorrect': False, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [], 'useranswerindexes': []},
    {'questionid': 268653526, 'no': 3, 'type': 1, 'correct': 0, 'totalscore': 0.0, 'score': None,
     'options': [{'iscorrect': False, 'chosed': False, 'index': 0, 'value': 'A'},
                 {'iscorrect': False, 'chosed': False, 'index': 1, 'value': 'B'},
                 {'iscorrect': False, 'chosed': False, 'index': 2, 'value': 'C'},
                 {'iscorrect': False, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [], 'useranswerindexes': []},
    {'questionid': 268653527, 'no': 4, 'type': 1, 'correct': 0, 'totalscore': 0.0, 'score': None,
     'options': [{'iscorrect': False, 'chosed': False, 'index': 0, 'value': 'A'},
                 {'iscorrect': False, 'chosed': False, 'index': 1, 'value': 'B'},
                 {'iscorrect': False, 'chosed': False, 'index': 2, 'value': 'C'},
                 {'iscorrect': False, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [], 'useranswerindexes': []}]},
                     {'no': 2, 'title': '二、判断题', 'type': 2, 'totalscore': 20.0, 'questioncnt': 2, 'details': [
                         {'questionid': 268653528, 'no': 1, 'type': 2, 'correct': 0, 'totalscore': 0.0, 'score': None,
                          'options': [{'iscorrect': False, 'chosed': False, 'index': 0, 'value': '正确'},
                                      {'iscorrect': False, 'chosed': False, 'index': 1, 'value': '错误'}],
                          'rightanswerindexes': [], 'useranswerindexes': []},
                         {'questionid': 268653529, 'no': 2, 'type': 2, 'correct': 0, 'totalscore': 0.0, 'score': None,
                          'options': [{'iscorrect': False, 'chosed': False, 'index': 0, 'value': '正确'},
                                      {'iscorrect': False, 'chosed': False, 'index': 1, 'value': '错误'}],
                          'rightanswerindexes': [], 'useranswerindexes': []}]},
                     {'no': 3, 'title': '三、填空题', 'type': 3, 'totalscore': 20.0, 'questioncnt': 2, 'details': [
                         {'questionid': 268653530, 'no': 1, 'type': 3, 'correct': 0, 'totalscore': 0.0, 'score': None,
                          'options': [], 'rightanswerindexes': [], 'useranswerindexes': []},
                         {'questionid': 268653531, 'no': 2, 'type': 3, 'correct': 0, 'totalscore': 0.0, 'score': None,
                          'options': [], 'rightanswerindexes': [], 'useranswerindexes': []}]},
                     {'no': 4, 'title': '四、解答题', 'type': 4, 'totalscore': 10.0, 'questioncnt': 1, 'details': [
                         {'questionid': 268653532, 'no': 1, 'type': 4, 'correct': 0, 'totalscore': 0.0, 'score': None,
                          'options': [], 'rightanswerindexes': [], 'useranswerindexes': []}]}] if get_env() == 'prod' else [
    {'no': 1, 'title': '一、选择题', 'type': 1, 'totalscore': 50.0, 'questioncnt': 5, 'details': [
        {'questionid': 1457, 'no': 1, 'type': 1, 'correct': 0, 'totalscore': 0.0, 'score': None,
         'options': [{'iscorrect': False, 'chosed': False, 'index': 0, 'value': 'A'},
                     {'iscorrect': False, 'chosed': False, 'index': 1, 'value': 'B'},
                     {'iscorrect': False, 'chosed': False, 'index': 2, 'value': 'C'},
                     {'iscorrect': False, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [], 'useranswerindexes': []},
        {'questionid': 1458, 'no': 2, 'type': 1, 'correct': 0, 'totalscore': 0.0, 'score': None,
         'options': [{'iscorrect': False, 'chosed': False, 'index': 0, 'value': 'A'},
                     {'iscorrect': False, 'chosed': False, 'index': 1, 'value': 'B'},
                     {'iscorrect': False, 'chosed': False, 'index': 2, 'value': 'C'},
                     {'iscorrect': False, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [], 'useranswerindexes': []},
        {'questionid': 1459, 'no': 3, 'type': 1, 'correct': 0, 'totalscore': 0.0, 'score': None,
         'options': [{'iscorrect': False, 'chosed': False, 'index': 0, 'value': 'A'},
                     {'iscorrect': False, 'chosed': False, 'index': 1, 'value': 'B'},
                     {'iscorrect': False, 'chosed': False, 'index': 2, 'value': 'C'},
                     {'iscorrect': False, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [], 'useranswerindexes': []},
        {'questionid': 1460, 'no': 4, 'type': 1, 'correct': 0, 'totalscore': 0.0, 'score': None,
         'options': [{'iscorrect': False, 'chosed': False, 'index': 0, 'value': 'A'},
                     {'iscorrect': False, 'chosed': False, 'index': 1, 'value': 'B'},
                     {'iscorrect': False, 'chosed': False, 'index': 2, 'value': 'C'},
                     {'iscorrect': False, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [], 'useranswerindexes': []},
        {'questionid': 1461, 'no': 5, 'type': 1, 'correct': 0, 'totalscore': 0.0, 'score': None,
         'options': [{'iscorrect': False, 'chosed': False, 'index': 0, 'value': 'A'},
                     {'iscorrect': False, 'chosed': False, 'index': 1, 'value': 'B'},
                     {'iscorrect': False, 'chosed': False, 'index': 2, 'value': 'C'},
                     {'iscorrect': False, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [], 'useranswerindexes': []}]},
    {'no': 2, 'title': '二、判断题', 'type': 2, 'totalscore': 20.0, 'questioncnt': 2, 'details': [
        {'questionid': 1462, 'no': 1, 'type': 2, 'correct': 0, 'totalscore': 0.0, 'score': None,
         'options': [{'iscorrect': False, 'chosed': False, 'index': 0, 'value': '正确'},
                     {'iscorrect': False, 'chosed': False, 'index': 1, 'value': '错误'}], 'rightanswerindexes': [], 'useranswerindexes': []},
        {'questionid': 1463, 'no': 2, 'type': 2, 'correct': 0, 'totalscore': 0.0, 'score': None,
         'options': [{'iscorrect': False, 'chosed': False, 'index': 0, 'value': '正确'},
                     {'iscorrect': False, 'chosed': False, 'index': 1, 'value': '错误'}], 'rightanswerindexes': [], 'useranswerindexes': []}]},
    {'no': 3, 'title': '三、填空题', 'type': 3, 'totalscore': 20.0, 'questioncnt': 2, 'details': [
        {'questionid': 1464, 'no': 1, 'type': 3, 'correct': 0, 'totalscore': 0.0, 'score': None, 'options': [],
         'rightanswerindexes': [], 'useranswerindexes': []},
        {'questionid': 1465, 'no': 2, 'type': 3, 'correct': 0, 'totalscore': 0.0, 'score': None, 'options': [],
         'rightanswerindexes': [], 'useranswerindexes': []}]}, {'no': 4, 'title': '四、解答题', 'type': 4, 'totalscore': 10.0, 'questioncnt': 1,
                                       'details': [
                                           {'questionid': 1466, 'no': 1, 'type': 4, 'correct': 0, 'totalscore': 0.0,
                                            'score': None, 'options': [], 'rightanswerindexes': [], 'useranswerindexes': []}]}]

rating_expect = [{'no': 3, 'title': '三、填空题', 'type': 3, 'totalscore': 20.0, 'questioncnt': 2, 'details': [
                         {'questionid': 268542161, 'no': 1, 'type': 3, 'correct': 0, 'totalscore': 10.0, 'score': None,
                          'options': [], 'rightanswerindexes': [], 'useranswerindexes': []},
                         {'questionid': 268542162, 'no': 2, 'type': 3, 'correct': 0, 'totalscore': 10.0, 'score': None,
                          'options': [], 'rightanswerindexes': [], 'useranswerindexes': []}]},
                     {'no': 4, 'title': '四、解答题', 'type': 4, 'totalscore': 10.0, 'questioncnt': 1, 'details': [
                         {'questionid': 268542163, 'no': 1, 'type': 4, 'correct': 0, 'totalscore': 10.0, 'score': None,
                          'options': [], 'rightanswerindexes': [], 'useranswerindexes': []}]}] if get_env() == 'prod' else [
    {'no': 3, 'title': '三、填空题', 'type': 3, 'totalscore': 20.0, 'questioncnt': 2, 'details': [
        {'questionid': 1464, 'no': 1, 'type': 3, 'correct': 0, 'totalscore': 10.0, 'score': None, 'options': [],
         'rightanswerindexes': [], 'useranswerindexes': []},
        {'questionid': 1465, 'no': 2, 'type': 3, 'correct': 0, 'totalscore': 10.0, 'score': None, 'options': [],
         'rightanswerindexes': [], 'useranswerindexes': []}]}, {'no': 4, 'title': '四、解答题', 'type': 4, 'totalscore': 10.0, 'questioncnt': 1,
                                       'details': [
                                           {'questionid': 1466, 'no': 1, 'type': 4, 'correct': 0, 'totalscore': 10.0,
                                            'score': None, 'options': [], 'rightanswerindexes': [], 'useranswerindexes': []}]}]

report_expect = [{'no': 1, 'title': '一、选择题', 'type': 1, 'totalscore': 50.0, 'questioncnt': 5, 'details': [
    {'questionid': 268542154, 'no': 1, 'type': 1, 'correct': 2, 'totalscore': 10.0, 'score': 10.0,
     'options': [{'iscorrect': True, 'chosed': True, 'index': 0, 'value': 'A'},
                 {'iscorrect': False, 'chosed': False, 'index': 1, 'value': 'B'},
                 {'iscorrect': False, 'chosed': False, 'index': 2, 'value': 'C'},
                 {'iscorrect': False, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [0],
     'useranswerindexes': [0]},
    {'questionid': 268542155, 'no': 2, 'type': 1, 'correct': 1, 'totalscore': 10.0, 'score': 0.0,
     'options': [{'iscorrect': False, 'chosed': True, 'index': 0, 'value': 'A'},
                 {'iscorrect': True, 'chosed': False, 'index': 1, 'value': 'B'},
                 {'iscorrect': False, 'chosed': False, 'index': 2, 'value': 'C'},
                 {'iscorrect': False, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [1],
     'useranswerindexes': [0]},
    {'questionid': 268542156, 'no': 3, 'type': 1, 'correct': 1, 'totalscore': 10.0, 'score': 0.0,
     'options': [{'iscorrect': False, 'chosed': True, 'index': 0, 'value': 'A'},
                 {'iscorrect': False, 'chosed': False, 'index': 1, 'value': 'B'},
                 {'iscorrect': True, 'chosed': False, 'index': 2, 'value': 'C'},
                 {'iscorrect': False, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [2],
     'useranswerindexes': [0]},
    {'questionid': 268542157, 'no': 4, 'type': 1, 'correct': 1, 'totalscore': 10.0, 'score': 0.0,
     'options': [{'iscorrect': False, 'chosed': True, 'index': 0, 'value': 'A'},
                 {'iscorrect': False, 'chosed': False, 'index': 1, 'value': 'B'},
                 {'iscorrect': False, 'chosed': False, 'index': 2, 'value': 'C'},
                 {'iscorrect': True, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [3],
     'useranswerindexes': [0]},
    {'questionid': 268542158, 'no': 5, 'type': 1, 'correct': 1, 'totalscore': 10.0, 'score': 0.0,
     'options': [{'iscorrect': False, 'chosed': True, 'index': 0, 'value': 'A'},
                 {'iscorrect': False, 'chosed': False, 'index': 1, 'value': 'B'},
                 {'iscorrect': True, 'chosed': False, 'index': 2, 'value': 'C'},
                 {'iscorrect': False, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [2],
     'useranswerindexes': [0]}]}, {'no': 2, 'title': '二、判断题', 'type': 2, 'totalscore': 20.0, 'questioncnt': 2,
                                   'details': [
                                       {'questionid': 268542159, 'no': 1, 'type': 2, 'correct': 2, 'totalscore': 10.0,
                                        'score': 10.0,
                                        'options': [{'iscorrect': True, 'chosed': True, 'index': 0, 'value': '正确'},
                                                    {'iscorrect': False, 'chosed': False, 'index': 1, 'value': '错误'}],
                                        'rightanswerindexes': [0], 'useranswerindexes': [0]},
                                       {'questionid': 268542160, 'no': 2, 'type': 2, 'correct': 1, 'totalscore': 10.0,
                                        'score': 0.0,
                                        'options': [{'iscorrect': False, 'chosed': True, 'index': 0, 'value': '正确'},
                                                    {'iscorrect': True, 'chosed': False, 'index': 1, 'value': '错误'}],
                                        'rightanswerindexes': [1], 'useranswerindexes': [0]}]},
                 {'no': 3, 'title': '三、填空题', 'type': 3, 'totalscore': 20.0, 'questioncnt': 2, 'details': [
                     {'questionid': 268542161, 'no': 1, 'type': 3, 'correct': 3, 'totalscore': 10.0, 'score': 9.0,
                      'options': [], 'rightanswerindexes': None, 'useranswerindexes': None},
                     {'questionid': 268542162, 'no': 2, 'type': 3, 'correct': 3, 'totalscore': 10.0, 'score': 9.0,
                      'options': [], 'rightanswerindexes': None, 'useranswerindexes': None}]},
                 {'no': 4, 'title': '四、解答题', 'type': 4, 'totalscore': 10.0, 'questioncnt': 1, 'details': [
                     {'questionid': 268542163, 'no': 1, 'type': 4, 'correct': 3, 'totalscore': 10.0, 'score': 9.0,
                      'options': [], 'rightanswerindexes': None, 'useranswerindexes': None}]}] if get_env() == 'prod' else [
    {'no': 1, 'title': '一、选择题', 'type': 1, 'totalscore': 50.0, 'questioncnt': 5, 'details': [
        {'questionid': 1457, 'no': 1, 'type': 1, 'correct': 2, 'totalscore': 10.0, 'score': 10.0,
         'options': [{'iscorrect': True, 'chosed': True, 'index': 0, 'value': 'A'},
                     {'iscorrect': False, 'chosed': False, 'index': 1, 'value': 'B'},
                     {'iscorrect': False, 'chosed': False, 'index': 2, 'value': 'C'},
                     {'iscorrect': False, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [0],
         'useranswerindexes': [0]},
        {'questionid': 1458, 'no': 2, 'type': 1, 'correct': 1, 'totalscore': 10.0, 'score': 0.0,
         'options': [{'iscorrect': False, 'chosed': True, 'index': 0, 'value': 'A'},
                     {'iscorrect': True, 'chosed': False, 'index': 1, 'value': 'B'},
                     {'iscorrect': False, 'chosed': False, 'index': 2, 'value': 'C'},
                     {'iscorrect': False, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [1],
         'useranswerindexes': [0]},
        {'questionid': 1459, 'no': 3, 'type': 1, 'correct': 1, 'totalscore': 10.0, 'score': 0.0,
         'options': [{'iscorrect': False, 'chosed': True, 'index': 0, 'value': 'A'},
                     {'iscorrect': False, 'chosed': False, 'index': 1, 'value': 'B'},
                     {'iscorrect': True, 'chosed': False, 'index': 2, 'value': 'C'},
                     {'iscorrect': False, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [2],
         'useranswerindexes': [0]},
        {'questionid': 1460, 'no': 4, 'type': 1, 'correct': 1, 'totalscore': 10.0, 'score': 0.0,
         'options': [{'iscorrect': False, 'chosed': True, 'index': 0, 'value': 'A'},
                     {'iscorrect': False, 'chosed': False, 'index': 1, 'value': 'B'},
                     {'iscorrect': False, 'chosed': False, 'index': 2, 'value': 'C'},
                     {'iscorrect': True, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [3],
         'useranswerindexes': [0]},
        {'questionid': 1461, 'no': 5, 'type': 1, 'correct': 1, 'totalscore': 10.0, 'score': 0.0,
         'options': [{'iscorrect': False, 'chosed': True, 'index': 0, 'value': 'A'},
                     {'iscorrect': False, 'chosed': False, 'index': 1, 'value': 'B'},
                     {'iscorrect': True, 'chosed': False, 'index': 2, 'value': 'C'},
                     {'iscorrect': False, 'chosed': False, 'index': 3, 'value': 'D'}], 'rightanswerindexes': [2],
         'useranswerindexes': [0]}]}, {'no': 2, 'title': '二、判断题', 'type': 2, 'totalscore': 20.0, 'questioncnt': 2,
                                       'details': [
                                           {'questionid': 1462, 'no': 1, 'type': 2, 'correct': 2, 'totalscore': 10.0,
                                            'score': 10.0,
                                            'options': [{'iscorrect': True, 'chosed': True, 'index': 0, 'value': '正确'},
                                                        {'iscorrect': False, 'chosed': False, 'index': 1,
                                                         'value': '错误'}], 'rightanswerindexes': [0],
                                            'useranswerindexes': [0]},
                                           {'questionid': 1463, 'no': 2, 'type': 2, 'correct': 1, 'totalscore': 10.0,
                                            'score': 0.0,
                                            'options': [{'iscorrect': False, 'chosed': True, 'index': 0, 'value': '正确'},
                                                        {'iscorrect': True, 'chosed': False, 'index': 1,
                                                         'value': '错误'}], 'rightanswerindexes': [1],
                                            'useranswerindexes': [0]}]},
    {'no': 3, 'title': '三、填空题', 'type': 3, 'totalscore': 20.0, 'questioncnt': 2, 'details': [
        {'questionid': 1464, 'no': 1, 'type': 3, 'correct': 3, 'totalscore': 10.0, 'score': 9.0, 'options': [],
         'rightanswerindexes': None, 'useranswerindexes': None},
        {'questionid': 1465, 'no': 2, 'type': 3, 'correct': 3, 'totalscore': 10.0, 'score': 9.0, 'options': [],
         'rightanswerindexes': None, 'useranswerindexes': None}]},
    {'no': 4, 'title': '四、解答题', 'type': 4, 'totalscore': 10.0, 'questioncnt': 1, 'details': [
        {'questionid': 1466, 'no': 1, 'type': 4, 'correct': 3, 'totalscore': 10.0, 'score': 9.0, 'options': [],
         'rightanswerindexes': None, 'useranswerindexes': None}]}]
